//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YJ.CMS.Model.ViewModel
{
    using System;
    using System.Collections.Generic;
    
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    
    public partial class CategoryView
    {
        [DisplayName("编号")]
        public int c_id { get; set; }

        [DisplayName("类型")]
        [Required(ErrorMessage = "类型不能为空")]
        public int c_type { get; set; }

        [DisplayName("名称")]
        [Required(ErrorMessage = "名称不能为空")]
        public string c_title { get; set; }

        [DisplayName("父级id")]
        public int parent_id { get; set; }

        public virtual ICollection<ContentsView> Contents { get; set; }
        public virtual ICollection<NewsView> News { get; set; }
        public virtual ICollection<ProductView> Product { get; set; }
    }
}
